version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "Kmaina32"
    groups:
      production-dependencies:
        patterns:
          - "next"
          - "react*"
          - "firebase"
          - "genkit"
      security-updates:
        patterns:
          - "*"
        update-types:
          - "security:patch"
    labels:
      - "security"
      - "dependencies"
