"use client";

import AuthedLayout from "@/components/layout/AuthedLayout";
import { Card } from "@/components/ui/card";
import { ArrowLeft } from "lucide-react";
import Link from "next/link";

export default function MarketsDocPage() {
  return (
    <AuthedLayout title="Market Documentation" subtitle="Asset Specification & Index Generation">
      <div className="max-w-4xl mx-auto space-y-8">
        <Link href="/help" className="inline-flex items-center text-[10px] font-bold uppercase tracking-widest text-[#6B7280] hover:text-[#0A0A0A] transition-colors">
          <ArrowLeft className="w-3.5 h-3.5 mr-1" /> Back to Help Center
        </Link>

        <section className="space-y-4">
          <div className="border-b-2 border-[#0A0A0A] pb-2">
            <h2 className="text-2xl font-bold uppercase tracking-tight text-[#0A0A0A]">Market Architecture</h2>
          </div>
          <p className="text-xs text-[#6B7280] leading-relaxed">
            Varban Markets provides access to a diverse registry of financial instruments. Our pricing feeds are derived from a combination of global exchange data and proprietary synthetic models to ensure 24/7 availability and professional volatility profiles.
          </p>
        </section>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <Card className="p-6 bg-white border-[#E4E4E4] space-y-3 border-t-4 border-t-[#0055FF]">
            <h3 className="text-xs font-bold uppercase tracking-wider text-[#0A0A0A]">Synthetic Indices</h3>
            <p className="text-[10px] text-[#6B7280] leading-relaxed">
              Proprietary indices that simulate real-world market movements using mathematical algorithms. These markets are active 24/7, providing consistent opportunities regardless of traditional exchange hours.
            </p>
          </Card>
          <Card className="p-6 bg-white border-[#E4E4E4] space-y-3 border-t-4 border-t-[#16835B]">
            <h3 className="text-xs font-bold uppercase tracking-wider text-[#0A0A0A]">High-Volatility Pairs</h3>
            <p className="text-[10px] text-[#6B7280] leading-relaxed">
              Curated currency and crypto pairs (e.g., BTC/USD, GBP/JPY) selected for their liquidity and execution speed. Pricing is aggregated from multiple global liquidity pools.
            </p>
          </Card>
        </div>

        <section className="space-y-4">
          <h3 className="text-xs font-bold uppercase tracking-widest text-[#0A0A0A] border-b border-[#E4E4E4] pb-2">Market Domains</h3>
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse text-[11px]">
              <thead>
                <tr className="bg-[#F7F7F5] border-b border-[#E4E4E4] text-[#6B7280] font-bold uppercase tracking-widest">
                  <th className="p-4">Domain</th>
                  <th className="p-4">Availability</th>
                  <th className="p-4">Settlement Style</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-[#E4E4E4] text-[#0A0A0A]">
                <tr>
                  <td className="p-4 font-bold">Forex & Commodities</td>
                  <td className="p-4">24/5 (Mon-Fri)</td>
                  <td className="p-4">Mid-Market Aggregation</td>
                </tr>
                <tr>
                  <td className="p-4 font-bold">Digital Assets</td>
                  <td className="p-4">24/7/365</td>
                  <td className="p-4">Exchange Liquidity Weighting</td>
                </tr>
                <tr>
                  <td className="p-4 font-bold">Synthetic Indices</td>
                  <td className="p-4">24/7/365</td>
                  <td className="p-4">Deterministic Algorithm</td>
                </tr>
              </tbody>
            </table>
          </div>
        </section>

        <Card className="p-8 bg-[#F7F7F5] border border-[#0055FF] space-y-4 shadow-sm border-l-4">
          <h4 className="text-xs font-bold uppercase tracking-widest text-[#0055FF]">Pricing Transparency</h4>
          <p className="text-[11px] text-[#6B7280] leading-relaxed">
            All pricing feeds at Varban Markets are subject to strict internal auditing. Every tick generated by our synthetic engine is logged with a unique millisecond timestamp, allowing for total auditability of trade outcomes against the historical feed. We ensure zero asymmetric slippage between the client terminal and the matching engine.
          </p>
        </Card>
      </div>
    </AuthedLayout>
  );
}
